version: "3.8"

services:
  db:
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3309:3306

  web:
    image: nginx:1.21.3-alpine
    ports:
      - 8000:8000
    volumes:
      - ./src:/workspace
      - ./src/static:/static
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    working_dir: /workspace
    depends_on:
      - app

  app:
    build: ./docker/python
    command: bash -c "./init.sh;"
    volumes:
      - ./src:/workspace
      - ./python/log:/tmp
    expose:
      - "8001"
      - "8002"
    depends_on:
      - db
      - redis
    links:
      - redis

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

volumes:
  db-store:
